### ISSUE TITLE
Coco's Chocolatiers website

### ISSUE THREAD

**Issue by guer0125** [guer0125/confectionery-website-prototype#1]
Hey there,

can you check my website so far.

I'd like to think i'm done, i did pass all the markbot requirements and everything works. going through the checklist i saw 

> Transparent pricing and
> Website is credible; with testimonials, references, credentials, contact information, location—and real people.

do we have to write pricing and testimonials etc?
I do have a link for contact info where my location's supposed to be

Do we have to have all the things listen on the checklist in week 15?

@thomasjbradley

Thank you,

**Comment by thomasjbradley** [comment]
It looks pretty good. You don’t *need* all those items—the website should feel like a full, real website though.

A couple improvements:

- I don’t love the location of the toggle nav button, it seems awkwardly placed
- Work on the spacing around the banner text: the button is too close to the bottom sentence
